import { Order, OrderStatus, CartItem } from '../../types';

const mockItems: CartItem[] = [
    { cartItemId: 'ci-1', id: 'm1', name: 'Chicken Karahi', description: '', price: 850, quantity: 1, imageUrl: '', inStock: true, category: 'Main' },
    { cartItemId: 'ci-2', id: 'm2', name: 'Roghni Naan', description: '', price: 60, quantity: 4, imageUrl: '', inStock: true, category: 'Bread' },
    { cartItemId: 'ci-3', id: 'm3', name: 'Zinger Burger', description: '', price: 450, quantity: 2, imageUrl: '', inStock: true, category: 'Fast Food' },
    { cartItemId: 'ci-4', id: 'm4', name: 'Fries (Large)', description: '', price: 200, quantity: 1, imageUrl: '', inStock: true, category: 'Sides' },
    { cartItemId: 'ci-5', id: 'm5', name: 'Mineral Water', description: '', price: 80, quantity: 2, imageUrl: '', inStock: true, category: 'Drinks' },
];

export const mockOrders: Order[] = [
    {
        id: 'ORD-A1B2',
        customerId: 'user-1',
        customerName: 'Aamir Khan',
        restaurantName: 'The Golden Spoon',
        restaurantPhone: '+923111222333',
        items: [mockItems[0], mockItems[1], mockItems[4]],
        status: OrderStatus.Delivered,
        date: '2024-07-25',
        deliveryAddress: '123 Gulshan-e-Iqbal, Karachi',
        restaurantAddress: '456 Tariq Road, Karachi',
        estimatedArrival: 'Delivered at 8:45 PM',
        bill: { subtotal: 1070, deliveryFee: 150, serviceFee: 50, discount: -100, total: 1170 },
        riderInfo: {
            name: 'Javed Miandad',
            phone: '+923001112223',
            vehicle: 'Motorbike',
            vehiclePlate: 'KHI-1234',
            rating: 4.9,
            avatarUrl: 'https://i.pravatar.cc/150?u=javed.miandad',
        },
        paymentMethod: 'Credit Card (Visa **** 4242)',
        notesForRestaurant: 'Please make the karahi extra spicy.',
        notesForRider: 'Please ring the bell twice. Leave at the door if no one answers.',
        chatHistory: [
            { sender: 'Rider', text: 'Hi Aamir, I am on my way with your order from The Golden Spoon.', timestamp: '8:20 PM' },
            { sender: 'Customer', text: 'Great, thank you!', timestamp: '8:21 PM' },
            { sender: 'Rider', text: 'I am approaching your location now.', timestamp: '8:40 PM' },
            { sender: 'Rider', text: 'I have arrived.', timestamp: '8:42 PM' },
            { sender: 'Customer', text: 'Okay, coming down.', timestamp: '8:43 PM' },
        ],
    },
    {
        id: 'ORD-C3D4',
        customerId: 'user-1',
        customerName: 'Aamir Khan',
        restaurantName: 'Burger Barn',
        restaurantPhone: '+923223334444',
        items: [mockItems[2], mockItems[3]],
        status: OrderStatus.Cancelled,
        date: '2024-07-20',
        deliveryAddress: '123 Gulshan-e-Iqbal, Karachi',
        restaurantAddress: '789 Bahadurabad, Karachi',
        estimatedArrival: 'Cancelled',
        bill: { subtotal: 1100, deliveryFee: 100, serviceFee: 40, discount: 0, total: 1240 },
        paymentMethod: 'Cash on Delivery',
    },
    {
        id: 'ORD-E5F6',
        customerId: 'user-2',
        customerName: 'Basit Ali',
        restaurantName: 'Pizza Max',
        restaurantPhone: '+923334445555',
        items: [
             { cartItemId: 'ci-6', id: 'p1', name: 'Fajita Sicilian Pizza (Large)', description: '', price: 1500, quantity: 1, imageUrl: '', inStock: true, category: 'Pizza' },
             { cartItemId: 'ci-7', id: 's1', name: 'Garlic Bread Supreme', description: '', price: 400, quantity: 1, imageUrl: '', inStock: true, category: 'Sides' },
        ],
        status: OrderStatus.Delivered,
        date: '2024-07-18',
        deliveryAddress: 'Apt 5, Clifton Block 2, Karachi',
        restaurantAddress: 'Shop 1, Khayaban-e-Ittehad, Karachi',
        estimatedArrival: 'Delivered at 9:15 PM',
        bill: { subtotal: 1900, deliveryFee: 200, serviceFee: 80, discount: 0, total: 2180 },
        riderInfo: {
            name: 'Kamran Akmal',
            phone: '+923445556667',
            vehicle: 'Motorbike',
            vehiclePlate: 'KHI-5678',
            rating: 4.7,
            avatarUrl: 'https://i.pravatar.cc/150?u=kamran.akmal',
        },
        paymentMethod: 'Credit Card (Mastercard **** 5555)',
        notesForRestaurant: 'No olives on the pizza please.',
        notesForRider: 'Call upon arrival.',
        chatHistory: [
             { sender: 'Rider', text: 'Hello, I have your order and I\'m on my way.', timestamp: '8:50 PM' },
             { sender: 'Customer', text: 'Thanks! See you soon.', timestamp: '8:51 PM' },
        ],
    },
];
